name: Quizly Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade python-telegram-bot

      - name: Run Telegram Bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          API_KEY: ${{ secrets.API_KEY }}
          YOUTUBE_API: ${{ secrets.YOUTUBE_API }}
          SEND_EMAIL: ${{ secrets.SEND_EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python "Telegram Bot/quizly_telegram_bot.py"